// 全站文案字典:中文 / 英文。键名按区块组织(nav / landing / app / ext)。
// 通过 i18n.jsx 的 t("区块.键") 取值;数组(steps/features/chips)整段返回,组件自行 map。
// 动态值用 {name} 占位,t(key, { name }) 时替换。

export const messages = {
  zh: {
    nav: {
      login: "登录",
      addChrome: "添加到 Chrome",
      logout: "退出登录",
    },
    landing: {
      eyebrow: "求职助手 · CHROME 扩展",
      h1a: "右键一下，",
      h1b: "看清这份工作",
      h1em: "配不配你的简历",
      sub: "Agent Bridge 读取当前招聘页，对照你的简历，几秒内给出匹配评分、优势与差距，还能就这个职位写好求职信——全程不用离开页面，不用复制粘贴到别处。",
      ctaMain: "添加到 Chrome — 免费",
      ctaAlt: "已有账号？登录管理简历",
      trust: "在 LinkedIn、Indeed、拉勾等任意招聘页都能用",
      stepsEyebrow: "▸ 怎么用",
      steps: [
        {
          n: "01",
          title: "上传简历",
          body: "上传一次 PDF，自动设为生效简历。换工作方向随时再传一份。",
        },
        {
          n: "02",
          title: "招聘页右键",
          body: "在任意职位页面右键，选「分析与简历匹配」。",
        },
        {
          n: "03",
          title: "秒得分析",
          body: "评分、优势、差距、建议，直接显示在当前页面上。",
        },
      ],
      featuresEyebrow: "▸ 你会拿到什么",
      features: [
        { tag: "匹配评分", body: "0–100 的总体契合度，先看这份工作值不值得投。" },
        { tag: "量身求职信", body: "针对这个职位生成可直接发送的求职信。" },
        { tag: "简历改进建议", body: "指出该补强的关键词与经历，对症下药。" },
        { tag: "页面摘要", body: "任意网页右键，几秒抓住核心信息。" },
      ],
      closeH: "下一份工作，先问问 Agent Bridge。",
      footerNote: "你的简历只用于为你生成分析。",
      footerLink: "登录 / 管理简历",
      inst: {
        job: "职位",
        cv: "简历",
        scoreLabel: "匹配度",
        ok: "优势",
        gap: "差距",
        chip1: "全栈经验贴合岗位要求",
        chip2: "AI 工程与交付经历突出",
        chip3: "简历未提 Node.js 实战",
      },
    },
    app: {
      brandSubtitle: "简历管理",
      loggedInFallback: "已登录",
      loading: "加载中…",
      upload: {
        title: "上传简历",
        desc: "支持 PDF;上传成功的最新简历会自动设为「生效」,匹配时使用它。",
        pick: "选择 PDF 上传",
        stageSigning: "申请上传地址…",
        stageUploading: "上传到云端…",
        stageParsing: "解析简历文本…",
        errPdfOnly: "目前仅支持 PDF 简历。",
        errParse: "简历解析失败，请换一份可复制文本的 PDF。",
        ok: "上传成功，已设为当前生效简历。",
      },
      list: {
        title: "我的简历",
        empty: "还没有简历，点上方按钮上传第一份。",
        unnamed: "未命名简历",
        chars: "{n} 字",
        setActive: "设为生效",
        delete: "删除",
      },
      badge: {
        wait: "解析中",
        ok: "可用",
        fail: "解析失败",
        active: "生效中",
      },
      footerPrivacy: "隐私政策",
    },
    ext: {
      title: "浏览器扩展",
      desc: "连接后，扩展将以你的身份调用网关、使用你的简历。",
      stateDetecting: "检测中…",
      stateNotInstalled: "未检测到扩展",
      stateNotConnected: "扩展已安装，未连接",
      stateConnected: "已连接",
      connectedBadge: "已连接 ✓",
      btnConnecting: "连接中…",
      btnConnect: "连接扩展",
      btnReconnect: "重新连接",
      errNotConnectedConfirm: "扩展已检测到，但未确认连接，请点「重新连接」重试。",
      errConnectNotConfirmed: "连接未被扩展确认，请重试。",
      diagnoseNoRuntime:
        "页面拿不到扩展通道：确认已安装 Agent Bridge 扩展、并在 chrome://extensions 点过「重新加载」；当前页须在 externally_connectable 允许的域名下（云端 / dev 域名，不是 127.0.0.1）。",
      diagnoseIdMismatch:
        "扩展已安装但 ID 不匹配：当前扩展 ID 与前端期望的 {extId} 不一致（多见于装了未含 manifest key 的旧版扩展，或商店分配了不同 ID）。请安装含固定 key 的版本，或用 VITE_EXTENSION_ID 覆盖。",
      installQuestion: "还没安装？",
      installDownload: "下载扩展 zip",
      installStepsBefore: "，解压后在 ",
      installStepsAfter:
        " 开启「开发者模式」→「加载已解压」选择该目录，再回来点「连接扩展」。",
    },
  },

  en: {
    nav: {
      login: "Log in",
      addChrome: "Add to Chrome",
      logout: "Log out",
    },
    landing: {
      eyebrow: "JOB-SEARCH COPILOT · CHROME EXTENSION",
      h1a: "One right-click —",
      h1b: "see if this job",
      h1em: "fits your résumé",
      sub: "Agent Bridge reads the job posting you're on, compares it against your résumé, and gives you a match score, strengths, and gaps in seconds — and it drafts a cover letter for that exact role. All without leaving the page or copy-pasting anything.",
      ctaMain: "Add to Chrome — free",
      ctaAlt: "Already have an account? Log in to manage your résumé",
      trust: "Works on LinkedIn, Indeed, and any job listing page",
      stepsEyebrow: "▸ HOW IT WORKS",
      steps: [
        {
          n: "01",
          title: "Upload your résumé",
          body: "Upload a PDF once; it's set as your active résumé automatically. Changing direction? Just upload another.",
        },
        {
          n: "02",
          title: "Right-click a job page",
          body: "On any job listing, right-click and choose “Analyze & match résumé”.",
        },
        {
          n: "03",
          title: "Instant analysis",
          body: "Score, strengths, gaps, and tips — shown right on the page you're reading.",
        },
      ],
      featuresEyebrow: "▸ WHAT YOU GET",
      features: [
        { tag: "Match score", body: "A 0–100 overall fit, so you know upfront whether this job is worth applying to." },
        { tag: "Tailored cover letter", body: "A ready-to-send cover letter written for this specific role." },
        { tag: "Résumé tips", body: "The keywords and experience to strengthen — targeted, not generic." },
        { tag: "Page summary", body: "Right-click any web page and grab the key points in seconds." },
      ],
      closeH: "Your next job? Ask Agent Bridge first.",
      footerNote: "Your résumé is only used to generate your analysis.",
      footerLink: "Log in / manage résumé",
      inst: {
        job: "Job",
        cv: "Résumé",
        scoreLabel: "Match",
        ok: "Strength",
        gap: "Gap",
        chip1: "Full-stack experience fits the role",
        chip2: "Strong AI engineering & delivery track record",
        chip3: "Résumé doesn't mention hands-on Node.js",
      },
    },
    app: {
      brandSubtitle: "Résumés",
      loggedInFallback: "Signed in",
      loading: "Loading…",
      upload: {
        title: "Upload résumé",
        desc: "PDF only. Your most recent successful upload is set as the active résumé and used for matching.",
        pick: "Choose a PDF",
        stageSigning: "Requesting upload URL…",
        stageUploading: "Uploading…",
        stageParsing: "Parsing résumé text…",
        errPdfOnly: "Only PDF résumés are supported for now.",
        errParse: "Couldn't parse the résumé. Try a PDF with selectable text.",
        ok: "Uploaded and set as your active résumé.",
      },
      list: {
        title: "My résumés",
        empty: "No résumés yet — upload your first with the button above.",
        unnamed: "Untitled résumé",
        chars: "{n} chars",
        setActive: "Set active",
        delete: "Delete",
      },
      badge: {
        wait: "Parsing",
        ok: "Ready",
        fail: "Failed",
        active: "Active",
      },
      footerPrivacy: "Privacy policy",
    },
    ext: {
      title: "Browser extension",
      desc: "Once connected, the extension calls the gateway as you and uses your résumé.",
      stateDetecting: "Detecting…",
      stateNotInstalled: "Extension not detected",
      stateNotConnected: "Installed, not connected",
      stateConnected: "Connected",
      connectedBadge: "Connected ✓",
      btnConnecting: "Connecting…",
      btnConnect: "Connect extension",
      btnReconnect: "Reconnect",
      errNotConnectedConfirm:
        "Extension detected, but the connection wasn't confirmed — click “Reconnect” to retry.",
      errConnectNotConfirmed: "The extension didn't confirm the connection. Please retry.",
      diagnoseNoRuntime:
        "This page can't reach the extension: make sure Agent Bridge is installed and that you've clicked “Reload” on chrome://extensions. The page must be on a domain allowed by externally_connectable (your cloud / dev domain, not 127.0.0.1).",
      diagnoseIdMismatch:
        "The extension is installed but its ID doesn't match: the current extension ID differs from the {extId} the frontend expects (usually an older build without the manifest key, or a different ID assigned by the store). Install the build with the fixed key, or override it with VITE_EXTENSION_ID.",
      installQuestion: "Not installed yet?",
      installDownload: "Download extension zip",
      installStepsBefore: ", unzip it, then in ",
      installStepsAfter:
        " enable “Developer mode” → “Load unpacked” and select that folder, then come back and click “Connect extension”.",
    },
  },
};
